/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.11/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    war
}

tasks.war {
    archiveFileName.set("diceThrow.war")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    // testImplementation("org.glassfish.jersey.test-framework:jeresy-test-framework-core:3.1.7")

    compileOnly("jakarta.security.enterprise:jakarta.security.enterprise-api:4.0.0")
    compileOnly("jakarta.ws.rs:jakarta.ws.rs-api:3.1.0")
    compileOnly("jakarta.platform:jakarta.jakartaee-api:10.0.0")
    compileOnly("org.eclipse.persistence:eclipselink:4.0.2")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform{
        excludeTags("IntegrationTest")
    }
}

tasks.register<Test>("integrationTest"){
    description = "Runs integration tests."
    group = "verification"
    useJUnitPlatform{
        includeTags("IntegrationTest")
    }  
}
